### ISSUE TITLE
Begin technical report

### ISSUE THREAD

**Issue by texascloud** [CamelBackNotation/cs373-idb#16]
[Read the project page](https://www.cs.utexas.edu/users/downing/cs373/projects/IDB1.html) for a breakdown of the requirements.

If you're doing this but didn't close #11 then just ask whoever closed that issue how they setup the Rackspace server.

Same thing as above but for issue #17 

[Link to Google Doc](https://docs.google.com/document/d/1Oyp6JX3vryr0GCN6gYlIDz84mLunjEgbCnItSCIsNMU/edit?usp=sharing)

**Comment by iOS4ever** [comment]
WTF yo. I was assigned! This is mine!

Started working on the wiki.

**Comment by iOS4ever** [comment]
So you can't have more than one assignee. Damn it.

**Comment by texascloud** [comment]
@wripley did this
