### ISSUE TITLE
Decide what entities to use

### ISSUE THREAD

**Issue by texascloud** [CamelBackNotation/cs373-idb#9]
Are we for sure going to create models for Companies, Games, and Timelines? I put Timelines so that our project would differ enough from another group doing something similar. I think it's a really cool idea ([look here for an implementation of a timeline](https://www.igdb.com/companies/nintendo)). We could allow users to specify a time range, genre, or average rating (or all of those!) to create a timeline of games that match the filter.

My only issue is how do we represent "timelines" as a table? I guess a user could potentially have separate timelines (like pre-existing ones?). Up to you guys if we should try to figure this out or scrap "Timelines" as one of the data entities for something else (but I still think the generation of timelines should stay as a feature cuz it's freaking COOL!).

**Comment by DouglasWiley** [comment]
Models are "Companies", "Games", and "Years"
